### ISSUE TITLE
Databaser

### ISSUE THREAD

**Issue by Gusben95** [Gusben95/Nyheter#11]
Databaser 
Databas för nyheter
- TItel 
- tags
- views
- Brödtext
- Flaggad
- - Vad den är flaggad för 
- 
Databas för användare ( krypterad ) 
- email 
- namn 
- lösenord
- tags 
- Är prenumerant ?
- när prenumeration går ut
-

**Comment by Kybbe** [comment]
User: {
    id: Number,
    name: String,
    email: String,
    password
    stillPaying: Boolean,
    subscriptionEnd: String,
    preference: [
      "", ""
    ]
  },
  Articles: [
    {
      title: String,
      shortDescription: String,
      mainText: String,
      categorys: String,
      author: Number,
      dateAdded: String,
      views: String,
      flags: [
        ""
      ]
      images: [
        "", ""
      ]
    },
  ],

**Comment by Twedmark** [comment]
Lägg till roll på users för att kunna sätta som läsare/skribent/admin osv
