### ISSUE TITLE
As a product owner I want to store articles in a database so that articles are saved

### ISSUE THREAD

**Issue by Luken95** [Gusben95/Nyheter#45]

**Comment by Kybbe** [comment]
User: {
id: Number,
name: String,
email: String,
password
stillPaying: Boolean,
subscriptionEnd: String,
preference: [
"", ""
]
},
Articles: [
{
title: String,
shortDescription: String,
mainText: String,
categorys: String,
author: Number,
dateAdded: String,
views: String,
flags: [
""
]
images: [
"", ""
]
},
],

**Comment by Kybbe** [comment]
Lägg till roll på users för att kunna sätta som läsare/skribent/admin osv
